### PR TITLE
(#181) make demos compile with glfw3

### PR DESCRIPTION
**Pull request by ldegen**
This is basically the same as PR #151.

### CODE REVIEW

**Comment by slembcke** [comment]
GLFW3 is all well and good. I use it in several of my other projects. The problem is that this will only work for Linux users. I've been meaning to replace GLFW with something that builds out of the box on Mac and Windows too. Windows devs in particular are very... vocal... when things don't just work and I already have to deal with the disaster that is MSVC support. In the past I supported them by shipping GLFW binaries, and that's not really sustainable.

Anyway, I think there are probably 3 branches floating around at this point for GLFW3 support including one I made that replaced the GL2 renderer with a GL3.3 one. A couple weeks ago I started a Sokol app version, and I'm pretty happy with this since it's pretty trivial to distribute as source. I just have to finish rewriting the renderer, and I'm hoping to do that this week or next.

**Comment by slembcke** [comment]
The demo app is mostly rewritten to run on top of sokol_app and sokol_gfx now. Need to double check that it compiles on Mac and Windows now, but I wouldn't turn down help testing on Linux. ;)

https://github.com/slembcke/Chipmunk2D/tree/sokol

**Comment by aismann** [comment]
@slembcke 
I have built a VS2019 version of your latest sokol branch.
After some small changes the sokol demo works great (debug and realease) on Windows.

**Comment by ldegen** [comment]
@slembcke just pulled your changes. I'm happy to report that the sokol branch compiles + runs out of the box on my linux box (Debian sid). I will do a more thoroughly test this evening.

**Comment by slembcke** [comment]
@aismann That's good to know. I used a bunch of C99 features that I assumed would need to be removed. I might bump up the minimum supported MSVC version to get better C99 compat... Will see I guess.

**Comment by ldegen** [comment]
@slembcke FYI: did a clean compile last night (both debug and release), toyed around with all of the demos. No issues, as far as I could tell. (Debian sid/X86_64)

**Comment by slembcke** [comment]
Merged to master! No longer reliant on a dead version of GLFW or an ancient GL2 renderer.

I'll stop poking this dead pull request now. ;)

**Pull request closed without merging**
