### PR TITLE
Add Swift support

### PR DESCRIPTION
**Pull request by colemancda**
Swift support without wrappers
Also dynamic framework target for Carthage

Addresses #132

### CODE REVIEW

**Comment by blazewicz** [comment]
Thats a lot of work you've put into this PR but most (if not all?) of your changes are clang specific and therefore can not be merged into this project.

Look what I get with GCC 5.4.0:

```
$ make 2>&1 > /dev/null | grep 'error' | wc -l
21
$ make 2>&1 > /dev/null | grep 'warning' | wc -l
147
```

**Comment by colemancda** [comment]
I can add ifdef statements so it's only available in Clang

**Comment by blazewicz** [comment]
I am -1 on that. Adding tons of preprocessor statements would introduce to much chaos in the code.

This is in principle a C99 library so if you want to use it with Swift you should make a wrapper, as they exist for  [many other languages](http://chipmunk-physics.net/bindingsAndPorts.php).

**Comment by slembcke** [comment]
Erm. Sorry for being late to this party. I have to agree with @blazewicz unfortunately. I've had to reject other language specific header changes for similar reasons. Had I accepted any of those pull requests, it already would have been impossible for you to get this far.

Some alternatives, though either is more work to you:

* We could include a patch file that users could apply to get all of the annotations, though this requires somebody to maintain it. Realistically, somebody would have to do that with the Swift changes anyway as I don't really use Swift. (Yet? Maybe someday, but not today)
* You could use the doc-src/extractProtos.rb script to build the list of functions, and make a patch that way. I use it in a similar way when generating documentation.

While one of the primary reasons that Chipmunk is a C library is to make it easier to bind to other languages, the headers still need to be readable as C code for documentation purposes. I do appreciate what you are doing, I just can't accept it as is.

**Comment by colemancda** [comment]
:( ok

**Comment by slembcke** [comment]
Sorry. :( Like I said, I appreciate what you are trying to do, and am open to alternatives like a patch or somesuch.

**Comment by s1ddok** [comment]
I think it is better to just create SPM entry. I have one in private, maybe will PR later. The bad news is Package.swift file will have to sit and in the root of repo and you may not like it. Swift annotations will not make it any easier to use in Swift as the code will not be Swifty anyway.

**Pull request closed without merging**
